### PR TITLE
Freshen up meta-files.

### PR DESCRIPTION
**Pull request by fluffywaffles**
Delete TODO since it's all been migrated to GH Issues, update README, and
move the rant about combat to COMBAT.md

@Executable-Games/core please comment with a :+1: once you have read this and we'll merge it into master.

### CODE REVIEW

**Comment by Skim74** [comment]
:+1:

**Comment by aaronkarp123** [comment]
Can't figure out how to give a thumbs up... But yeah looks good

**Comment by fluffywaffles** [comment]
@aaronkarp123 thumbs up is `:+1:`

All emoji are accessed using `:<emoji-code>:` :sunglasses:

**Comment by dabomb2654** [comment]
:+1:

**Pull request merged**
