### PR TITLE
End screen

### PR DESCRIPTION
**Pull request by aaronkarp123**
Added unit groups based on alliance, added implementation for
determining health and death-states.

### CODE REVIEW

**Comment by fluffywaffles** [comment]
I am going to try to merge branch unitgroupcontroller-enumerator with this branch

**Comment by fluffywaffles** [comment]
Okay; @aaronkarp123 @dabomb2654 please review.

@dabomb2654 you will want to use the `UnitsCollection.CycleNext` method from UnitGroupController for targetting.

**Comment by fluffywaffles** [comment]
This PR addresses both #20 UnitGroupController units enumerator and  #6 End Screen

It closes #20 and lays out the basics for closing #6

**Comment by dabomb2654** [comment]
:+1:

**Pull request merged**
